version: "3"
services:
  mysql:
    image: mysql:5.7 
    container_name: mygame-mysql
    command: mysqld --user=root
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql      
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=MyGame
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
