version: "3"
services:
  postgres:
    container_name:
      mygame-postgres
    image: postgres
    restart: always
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '15432:5432'
    volumes:
      - '${POSTGRES_VOLUME}:/var/lib/postgresql/data'
    networks:
      - mygame

  pgadmin:
    container_name:
      mygame-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:      
      - ${PGADMIN_VOLUME}:/pgdata
    ports:
      - '8001:80'
    depends_on:
      - postgres
    networks:
      - mygame

  # gameserver:
  #   container_name:
  #     mygame-app
  #   build: 
  #     context: .    
  #   ports:
  #     - "8090:8090"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - mygame
  #   command: >
  #     bash -c 
  #       "cd /src/gameserver && ./gameserver"    

networks: 
  mygame:
    driver: bridge

volumes:
  postgres:
  pgadmin: